[build]
  command = "yarn build"
  publish = "out"  # Ensure this is consistent with your project structure

[context.production]
  command = "yarn build"
  publish = "out"  # This can be removed if it's the same as in the [build] section

# Optional: Define redirects or rewrites if needed
[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/api/index.js"
  status = 200
