[build]
  command = "yarn build"
  publish = "out"  
[context.production]
  command = "yarn build"
  publish = "out"  

# Optional: Define redirects or rewrites if needed
[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/api/index.js"
  status = 200
