[build]
command = "npm run build && npm run export"
publish = "out"

[[redirects]]
from = "/old-path"
to = "/new-path"
status = 301
force = true

[[redirects]]
from = "/api/*"
to = "/api/index.js"
status = 200
force = true
